server:
  port: 8484
spring:
  application:
    name: RATING-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/micorservices_ratings
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:configserver:http://localhost:8181

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka